"""empty message

Revision ID: 558a1ca4b77
Revises: 398ea67dcb9
Create Date: 2014-06-19 06:52:17.814860

"""

# revision identifiers, used by Alembic.
revision = '558a1ca4b77'
down_revision = '398ea67dcb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
